#ifndef TYPECODE
#error "You must define TYPECODE macro before include this file"
#endif

TYPECODE(TXD_TYPE_MT,   _T("MT"))
TYPECODE(TXD_TYPE_RF,   _T("RF"))
TYPECODE(TXD_TYPE_PF,   _T("PF"))
TYPECODE(TXD_TYPE_AP,   _T("AP"))
//TXD_TYPE_AD,
TYPECODE(TXD_TYPE_AF,   _T("AF"))
TYPECODE(TXD_TYPE_LF,   _T("LF"))
TYPECODE(TXD_TYPE_LC,   _T("LC"))
TYPECODE(TXD_TYPE_LM,   _T("LM"))
TYPECODE(TXD_TYPE_CT,   _T("CT"))
//TXD_TYPE_CV,
//TXD_TYPE_CN,
TYPECODE(TXD_TYPE_SR,   _T("SR"))
TYPECODE(TXD_TYPE_SP,   _T("SP"))
TYPECODE(TXD_TYPE_GS,   _T("GS"))
TYPECODE(TXD_TYPE_GT,   _T("GT"))
TYPECODE(TXD_TYPE_TB,   _T("TB"))
TYPECODE(TXD_TYPE_TS,   _T("TS"))
TYPECODE(TXD_TYPE_TG,   _T("TG"))
TYPECODE(TXD_TYPE_DJ,   _T("DJ"))
TYPECODE(TXD_TYPE_BF,   _T("BF"))
TYPECODE(TXD_TYPE_JV,   _T("JV"))
TYPECODE(TXD_TYPE_VC,   _T("VC"))
TYPECODE(TXD_TYPE_VS,   _T("VS"))
TYPECODE(TXD_TYPE_END,  _T("END"))
TYPECODE(TXD_TYPE_NONE, _T("NONE"))